### ISSUE TITLE
Go to frame

### ISSUE THREAD

**Issue by pqmmw169** [vladimirnetworks/SwiperBox#2]
Hi Vladimir,
Your scripts rocks !!!

But I have a feature request.

Is there a way to use a function to swipe the gallery?

I need to click on some links on my page and have the gallery scrolling automatically to a specific frame.
It would be really awesome !!!

Thank you very much and keep the good work.

Michel

**Comment by vladimirnetworks** [comment]
Hi Michel
Thank you for your attention to my repo
I added a new method called GoTo to the script
You can use it to swipe any item.

you can see a live example here
https://stackblitz.com/edit/web-platform-cvdtaj?file=index.html

best regards.

**Comment by pqmmw169** [comment]
Hi Vladimir,

Thank you! It's simply perfect !!!

Best regards.
